/**
 * category.js - Category Management Logic
 */

const CategoryModule = {
    categories: [],

    fetchCategories: function() {
        fetch(`${API_BASE}/category`)
            .then(response => {
                if(!response.ok && response.status !== 400) throw new Error('Network response was not ok');
                return response.json();
            })
            .then(res => {
                if (res.status === 200 || res.status === 201) {
                    this.categories = res.data || [];
                    this.renderTable();
                } else {
                    App.showToast(res.massage || 'Failed to load categories.', 'error');
                }
            })
            .catch(error => {
                console.error('Error fetching categories:', error);
                App.showToast('Failed to load categories.', 'error');
            });
    },

    renderTable: function(data = this.categories) {
        const tbody = document.getElementById('category-table-body');
        if (!tbody) return;
        
        if (data.length === 0) {
            tbody.innerHTML = '<tr><td colspan="3" class="px-6 py-8 text-center text-gray-500 dark:text-gray-400 bg-gray-50/50 dark:bg-gray-800/50">No categories found.</td></tr>';
            return;
        }
        
        let html = '';
        data.forEach(cat => {
            html += `
                <tr class="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors border-b border-gray-100 dark:border-gray-800">
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-gray-100">${cat.id}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">${cat.name}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button onclick='CategoryModule.edit(${JSON.stringify(cat)})' class="text-brand-600 dark:text-brand-400 hover:text-brand-900 dark:hover:text-brand-300 mr-3 p-1 rounded hover:bg-brand-50 dark:hover:bg-brand-900/30 transition-colors">
                            <i class="fa-solid fa-pen"></i>
                        </button>
                        <button onclick="CategoryModule.delete(${cat.id})" class="text-red-600 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300 p-1 rounded hover:bg-red-50 dark:hover:bg-red-900/30 transition-colors">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </td>
                </tr>
            `;
        });
        tbody.innerHTML = html;
    },

    handleSearch: function(query) {
        const filtered = this.categories.filter(c => 
            c.id.toString().includes(query) || 
            c.name.toLowerCase().includes(query.toLowerCase())
        );
        this.renderTable(filtered);
    },

    setupModal: function(mode, data) {
        document.getElementById('categoryFormMode').value = mode;
        document.getElementById('categoryModalTitle').innerText = mode === 'create' ? 'Add New Category' : 'Edit Category';
        
        if (mode === 'edit' && data) {
            document.getElementById('categoryID').value = data.id;
            document.getElementById('categoryName').value = data.name;
        } else {
            document.getElementById('categoryID').value = "0"; // ID is auto-generated by DB since it's an int
            document.getElementById('categoryName').value = "";
        }
    },

    handleSubmit: function(e) {
        e.preventDefault();
        
        const mode = document.getElementById('categoryFormMode').value;
        const categoryData = {
            id: parseInt(document.getElementById('categoryID').value) || 0,
            name: document.getElementById('categoryName').value
        };
        
        const method = mode === 'create' ? 'POST' : 'PUT';
        
        fetch(`${API_BASE}/category`, {
            method: method,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(categoryData)
        })
        .then(response => response.json().catch(() => ({ massage: 'Server error' })))
        .then(res => {
            if (res.status === 200 || res.status === 201) {
                App.showToast(`Category ${mode === 'create' ? 'created' : 'updated'} successfully!`);
                App.closeModal('categoryModal');
                this.fetchCategories();
            } else {
                App.showToast(res.massage || 'Operation failed.', 'error');
            }
        })
        .catch(err => {
            console.error(err);
            App.showToast('An error occurred while saving.', 'error');
        });
    },

    edit: function(cat) {
        App.openModal('categoryModal', 'edit', cat);
    },

    delete: function(id) {
        if (!confirm(`Are you sure you want to delete category ${id}?`)) return;
        
        fetch(`${API_BASE}/category/${id}`, {
            method: 'DELETE'
        })
        .then(response => response.json().catch(() => ({ massage: 'Server error' })))
        .then(res => {
            if (res.status === 200) {
                App.showToast('Category deleted successfully!');
                this.fetchCategories();
            } else {
                App.showToast(res.massage || 'Failed to delete.', 'error');
            }
        })
        .catch(err => {
            console.error(err);
            App.showToast('An error occurred while deleting.', 'error');
        });
    }
};
